import assert from 'node:assert/strict';import{seed,validate,accept,safeURL,remaining,COOLDOWN,ageShade,MAX_LENGTH,pathLength,extendPath,nearestStroke}from'./src/core.mjs';const p=[[100,100],[120,130],[130,100]];let s=seed();assert.equal(s.length,47);let r=accept(s,0,p,'https://example.com',1000);assert.equal(r.strokes.length,47);assert.equal(r.strokes[0].id,'seed-1');assert.equal(r.nextAllowed,1000+300000);assert.throws(()=>accept(r.strokes,r.nextAllowed,p,'',1001));assert.equal(remaining(3600000,0),'60:00');assert.equal(remaining(3600000,1000),'59:59');assert.equal(remaining(1,5),'00:00');for(const u of ['javascript:alert(1)','http://example.com','https://localhost','https://127.0.0.1','https://a:b@example.com','https://host.local','https://foo.localhost','https://localhost.','https://machine.local.','https://host.internal.'])assert.throws(()=>safeURL(u));assert.equal(validate([[0,0],[960,480]],'').points.length,2);assert.throws(()=>validate([[1,1],[NaN,1]],''));let circle=Array.from({length:100},(_,i)=>[100+70*Math.cos(i/99*Math.PI*2),100+70*Math.sin(i/99*Math.PI*2)]);assert.equal(validate(circle,'').points.length,100);assert.equal(COOLDOWN,300000);console.log('core: 23 assertions pass');

const palette=Array.from({length:47},(_,i)=>ageShade(i));assert.equal(new Set(palette).size,47);assert.equal(palette[0],"#8a8a8a");assert.equal(palette[46],"#000000");assert.equal(ageShade(45),"#030303");let old=seed();const positions=old[10].points;let next=accept(old,0,p,"",1).strokes;assert.deepEqual(next[9].points,positions);assert.notEqual(ageShade(10),ageShade(9));console.log("age palette: 47 unique shades, eviction lightens survivors without moving points");

assert.equal(MAX_LENGTH,2880);let line=[[0,0],[960,0],[960,480],[0,480]];line=extendPath(line,[0,0]);assert.equal(pathLength(line),2880);assert.equal(validate(line,"").points.length,5);assert.deepEqual(extendPath(line,[100,100]),line);assert.throws(()=>validate([...line,[1,0]],""));let partial=extendPath([[0,0],[960,0],[960,480],[0,480]],[480,0]);assert.ok(Math.abs(pathLength(partial)-2880)<0.001);console.log("perimeter cap, full-canvas gestures, partial endpoint and freeze tests pass");

const zigzag=Array.from({length:126},(_,i)=>[100+(i%2)*20,100]);const exact=validate(zigzag,"").points;assert.deepEqual(exact,zigzag);assert.equal(pathLength(exact),2500);assert.deepEqual(accept(seed(),0,zigzag,"",100).strokes.at(-1).points,zigzag);console.log("126point zigzag preserved exactly, 2500length unchanged");

assert.equal(remaining(COOLDOWN,0),"05:00");const linked={id:"test",points:[[0,0],[100,100]],url:"https://example.com"};assert.equal(nearestStroke([linked],[50,50]).url,linked.url);assert.equal(nearestStroke([linked],[300,300]),null);console.log("5 minute cooldown and hit test pass");
