export const WIDTH=960, HEIGHT=480, COOLDOWN=300000, MAX_LENGTH=2*(WIDTH+HEIGHT);
export function seed(){return Array.from({length:47},(_,i)=>{const t=i/46,x=70+t*820,y=220+65*Math.sin(t*Math.PI*3);return {id:'seed-'+i,points:[[Math.round(x),Math.round(y-60)],[Math.round(x+22),Math.round(y)],[Math.round(x-12),Math.round(y+70)]],url:''};});}
export function safeURL(input){if(!input.trim())return '';if(input.length>160)throw Error('Keep the link under 160 characters.');let u;try{u=new URL(input)}catch{throw Error('Use a complete HTTPS link.')}const h=u.hostname.toLowerCase().replace(/\.+$/,'');if(u.protocol!=='https:'||u.username||u.password||!h.includes('.')||h==='localhost'||h.endsWith('.localhost')||h.endsWith('.local')||h.endsWith('.internal')||/^[\d.]+$/.test(h)||h.includes(':'))throw Error('Use a public HTTPS link without login details.');return u.href;}
export function validate(points,url){if(!Array.isArray(points)||points.length<2||points.length>1536)throw Error('Draw one continuous line.');if(points.some(p=>!Array.isArray(p)||p.length!==2||p.some(v=>!Number.isFinite(v))||p[0]<0||p[0]>WIDTH||p[1]<0||p[1]>HEIGHT))throw Error('Keep the line inside the canvas.');const len=pathLength(points);if(len<5||len>MAX_LENGTH+0.001)throw Error('Use a line between 5 pixels and one canvas perimeter long.');return {points:points.map(p=>[...p]),url:safeURL(url)};}
export function accept(strokes,nextAllowed,points,url,now){if(now<nextAllowed)throw Error('The canvas is resting. Your draft is kept.');const stroke=validate(points,url);return {strokes:[...strokes.slice(-46),{...stroke,id:'stroke-'+now}],nextAllowed:now+COOLDOWN};}
export function remaining(next,now){const seconds=Math.max(0,Math.ceil((next-now)/1000));return String(Math.floor(seconds/60)).padStart(2,'0')+':'+String(seconds%60).padStart(2,'0');}

// index 0 is oldest. All 47 distinct opaque grays stay visible on white.
export function ageShade(index,total=47){const value=Math.round(138*(total-1-index)/Math.max(1,total-1));const hex=value.toString(16).padStart(2,"0");return "#"+hex.repeat(3);}

export function pathLength(points){let n=0;for(let i=1;i<points.length;i++)n+=Math.hypot(points[i][0]-points[i-1][0],points[i][1]-points[i-1][1]);return n;}
export function extendPath(points,p){if(!points.length)return [p];const last=points.at(-1),distance=Math.hypot(p[0]-last[0],p[1]-last[1]),left=Math.max(0,MAX_LENGTH-pathLength(points));if(!left||!distance||points.length>=1536)return points;if(distance<=left)return [...points,p];const t=left/distance;return [...points,[last[0]+(p[0]-last[0])*t,last[1]+(p[1]-last[1])*t]];}

export function nearestStroke(strokes,p,radius=18){let nearest=null,d=radius;for(const s of strokes)for(let i=1;i<s.points.length;i++){const x=s.points[i-1],y=s.points[i],vx=y[0]-x[0],vy=y[1]-x[1],t=Math.max(0,Math.min(1,((p[0]-x[0])*vx+(p[1]-x[1])*vy)/(vx*vx+vy*vy||1))),dist=Math.hypot(p[0]-x[0]-t*vx,p[1]-x[1]-t*vy);if(dist<d){nearest=s;d=dist}}return nearest;}
